### ISSUE TITLE
Dimension error in inception_blocks_v2.py

### ISSUE THREAD

**Issue by bicsu** [akshaybahadur21/Facial-Recognition-using-Facenet#17]
Traceback (most recent call last):
  File "Train-inception.py", line 38, in <module>
    main()
  File "Train-inception.py", line 33, in main
    FRmodel = faceRecoModel(input_shape=(3, 96, 96))
  File "/home/pirl/Downloads/ken/Classes/FACENET_CLONED/Facial-Recognition-using-Facenet/inception_blocks_v2.py", line 260, in faceRecoModel
    X = inception_block_1a(X)
  File "/home/pirl/Downloads/ken/Classes/FACENET_CLONED/Facial-Recognition-using-Facenet/inception_blocks_v2.py", line 48, in inception_block_1a
    inception = concatenate([X_3x3, X_5x5, X_pool, X_1x1], axis=2)
  File "/home/pirl/anaconda3/envs/facenet/lib/python3.6/site-packages/keras/layers/merge.py", line 641, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/home/pirl/anaconda3/envs/facenet/lib/python3.6/site-packages/keras/engine/topology.py", line 594, in __call__
    self.build(input_shapes)
  File "/home/pirl/anaconda3/envs/facenet/lib/python3.6/site-packages/keras/layers/merge.py", line 354, in build
    'Got inputs shapes: %s' % (input_shape))
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 128, 12, 192), (None, 32, 12, 192), (None, 32, 12, 102), (None, 64, 12, 192)

this error has been occred when run `Train_inception.py`

**Comment by SunnyCOV** [comment]
Same Issue, Did anyone find the solution for this?

**Comment by SunnyCOV** [comment]
@akshaybahadur21 @mauryasameer @bicsu

**Comment by nitin-kamath** [comment]
did you find a solution for this?
