### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by kkpriyankacoding** [akshaybahadur21/Facial-Recognition-using-Facenet#3]
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Segmentation fault (core dumped)

**Comment by akshaybahadur21** [comment]
Can you please provide the full stack trace

**Comment by ashd758** [comment]
Traceback (most recent call last):
  File "rec-feat.py", line 112, in <module>
    recognize()
  File "rec-feat.py", line 103, in recognize
    extract_face_info(img, img_rgb, database,ear)
  File "rec-feat.py", line 59, in extract_face_info
    name, min_dist = recognize_face(image, database)
  File "rec-feat.py", line 44, in recognize_face
    if int(identity) <=4:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[ WARN:0] terminating async callback

**Comment by Obaei** [comment]
hi 
please help me

Traceback (most recent call last):
  File "D:/File Folder/Collage [semnan University ]/MS VS/Facial-Recognition-using-Facenet-master/Facial-Recognition-using-Facenet-master/rec-feat.py", line 7, in <module>
    from keras.models import load_model
  File "D:\ProgramData\Anaconda3\envs\new\lib\site-packages\keras\__init__.py", line 20, in <module>
    from . import initializers
  File "D:\ProgramData\Anaconda3\envs\new\lib\site-packages\keras\initializers\__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "D:\ProgramData\Anaconda3\envs\new\lib\site-packages\keras\initializers\__init__.py", line 82, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

Process finished with exit code 1
