### ISSUE TITLE
bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by tec-gopi** [akshaybahadur21/Facial-Recognition-using-Facenet#8]
Using TensorFlow backend.
Traceback (most recent call last):
  File "rec-feat.py", line 13, in <module>
    FRmodel = load_model('face-rec_Google.h5')
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2510, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2496, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 711, in from_config
    function = func_load(config['function'], globs=globs)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py", line 234, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

while trying to run the rec-feat.py facing this error

**Comment by patilameya825** [comment]
Use python3.5. It worked for me.

**Comment by NishantSinghChandel** [comment]
I am facing the same issue with python 3.8.

**Comment by xugaoxiang** [comment]
Same error, python3.8 anaconda。

3.7.10 works.

**Comment by salimi-erfan** [comment]
Same error, python3.10 :(
